Tweak CI

diff --git a/.github/actions/setup-nodejs-pnpm/action.yml b/.github/actions/setup-nodejs-pnpm/action.yml
--- a/.github/actions/setup-nodejs-pnpm/action.yml
+++ b/.github/actions/setup-nodejs-pnpm/action.yml
@@ -19,11 +19,22 @@ inputs:
   install-recursive:
     description: "Whether to install dependencies recursively"
     required: false
-    default: "true"
+    default: "false"
+  install-filter:
+    description: "Name of the target package whose dependencies should be installed"
+    required: false
+    default: ""
 
 runs:
   using: composite
   steps:
+    - name: Check inputs
+      shell: bash
+      run: |
+        if [[ "${{ inputs.install-recursive }}" == "true" && -n "${{ inputs.install-filter }}" ]]; then
+          echo "Error: install-recursive and install-filter cannot be used together"
+          exit 1
+        fi
     - name: Setup pnpm
       id: pnpm-setup
       uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
@@ -42,9 +53,9 @@ runs:
       if: ${{ inputs.prod == 'true' }}
       working-directory: ${{ inputs.working-dir }}
       shell: bash
-      run: pnpm ${{ inputs.install-recursive && '--recursive' || '' }} install
+      run: pnpm ${{ inputs.install-recursive && '--recursive' || '' }} ${{ inputs.install-filter && '--filter inputs.install-filter' || '' }} install --prod
     - name: Install dependencies
       if: ${{ inputs.prod != 'true' }}
       working-directory: ${{ inputs.working-dir }}
       shell: bash
-      run: pnpm ${{ inputs.install-recursive && '--recursive' || '' }} install
+      run: pnpm ${{ inputs.install-recursive && '--recursive' || '' }} ${{ inputs.install-filter && '--filter inputs.install-filter' || '' }} install
