Fix workflows

diff --git a/.github/workflows/frontend-infrastructure-plan.yml b/.github/workflows/frontend-infrastructure-plan.yml
--- a/.github/workflows/frontend-infrastructure-plan.yml
+++ b/.github/workflows/frontend-infrastructure-plan.yml
@@ -18,15 +18,6 @@ jobs:
     runs-on: ubuntu-latest
     environment: production
     steps:
-      - name: Make config
-        working-directory: ./packages/frontend-infrastructure/scripts
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_REGION: ${{ vars.AWS_REGION }}
-          AWS_S3_BUCKET_NAME: ${{ vars.AWS_S3_BUCKET_NAME }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        run: |
-          echo "FRONTEND_INFRASTRUCTURE_JSON_CONFIG=$(mk_config.sh)" >>"$GITHUB_ENV"
       - name: Checkout repo
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
       - uses: ./.github/actions/setup-nodejs-pnpm
@@ -42,6 +33,20 @@ jobs:
       #     audience: sts.amazonaws.com
       #     aws-region: ${{ vars.AWS_REGION }}
       #     role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/FrontendAppDeploy
+      - name: Make config
+        working-directory: ./packages/frontend-infrastructure/scripts
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_REGION: ${{ vars.AWS_REGION }}
+          AWS_S3_BUCKET_NAME: ${{ vars.AWS_S3_BUCKET_NAME }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        run: |
+          config_json=$(./mk_config.sh)
+          if [ $? -ne 0 ]; then
+            echo "Failed to create config"
+            exit 1
+          fi
+          echo "FRONTEND_INFRASTRUCTURE_JSON_CONFIG=$config_json" >>"$GITHUB_ENV"
       - name: Get CDKTF version
         id: get-cdktf-version
         run: |
@@ -51,7 +56,9 @@ jobs:
         working-directory: ./packages/frontend-infrastructure
         run: pnpx cdktf-cli@${{ steps.get-cdktf-version.outputs.cdktf-version }} get
       - name: Terraform plan
-        uses: hashicorp/terraform-cdk-action@v5
+        uses: hashicorp/terraform-cdk-action@d0ac1a0d6ea11736459c4e06ccf55a5fda705f77 # v5.0.1
+        env:
+          FRONTEND_INFRASTRUCTURE_JSON_CONFIG: ${{ env.FRONTEND_INFRASTRUCTURE_JSON_CONFIG }}
         with:
           cdktfVersion: ${{ steps.get-cdktf-version.outputs.cdktf-version }}
           githubToken: ${{ secrets.GITHUB_TOKEN }}
